services:
  database:
    container_name: db-mediawiki
    image: mysql:5.7.40
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    network_mode: bridge
  mediawiki:
    container_name: mediawiki
    depends_on:
      - database
    build:
      dockerfile_inline: |
        FROM php:7.2.24-apache
        RUN docker-php-ext-install mysqli
    restart: always
    links:
      - database
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/apache2
    environment:
      VIRTUAL_HOST: drake.sharcnet.ca
      LETSENCRYPT_HOST: drake.sharcnet.ca
    network_mode: bridge
