services:
  database:
    container_name: db-mediawiki
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    network_mode: bridge
  mediawiki:
    container_name: mediawiki
    image: mediawiki
    restart: always
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      VIRTUAL_HOST: drake.techiteasy.ca
      LETSENCRYPT_HOST: drake.techiteasy.ca
    network_mode: bridge
