services:
  database:
    container_name: db-mediawiki
    image: mysql:5.7.40
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    network_mode: bridge
  mediawiki:
    container_name: mediawiki
    depends_on:
      - database
    build:
      dockerfile_inline: |
        FROM php:7.2.24-apache
        RUN docker-php-ext-install mysqli
        RUN ln -sf /dev/stdout /var/log/nginx/access.log
        RUN ln -sf /dev/stderr /var/log/nginx/error.log
    restart: always
    links:
      - database
    volumes:
      - ./html:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    logging:
      options:
        max-size: 50m
    environment:
      VIRTUAL_HOST: drake.sharcnet.ca
      LETSENCRYPT_HOST: drake.sharcnet.ca
    network_mode: bridge
